---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jupyter-auth
  namespace: jupyter
spec:
  encryptedData:
    password: AgANMfy1O4aJRQT+PIws1qb5zKZKOq0GXmoGpgwoTMAeC4n36xbFFRtERNYcSaPaenqHMTxnDZurpF+gXC1soeyuR6lRRzxy+xqKaJCfJeqXT9DFl097j7BbAfy9Yfqt+74VtuWdrT6mQMpFgd85HQOKDfYWyPDV/SGoHAwZxT/yEv960Qe6S6aeZMiwu7uqq95xX+BYx3V5nGyHdtWaCPCVOMqPwx69zOiNm57YIUDrafmM/X6j7fKFpX1H9QwtwFReXRYrnGNZBHVps9q+zeNI2u7lN6Rv54KXShcCJmQJR6wVT3rCOUI0s4YB8EeT5/LogCAjXpwBtSahUiZLRyHAOp552OC3Yx7HINg2yj+3b9uU8BBzJ4Azxu+fo+HWsuUq8da5J9ERhSzfGW+zK1Fj9WKVosd9ma0Nltv8j8DaOtlbMMmyWIE91ag2rp3ooDlz6zH8xf9VeCCoyaQZuKHXZinyI4+iLMYD2cTUXusNWi9lm+EXUepP6kW0F/JFe4eHGGoFs7NwfbIPkmaLdRrlJN8tYdre9j24WfPh92ZtBUpuJw1nY7LiBk00+7b+4+8oHOgKvBQbfVAT3PXQad1mw498GVMYGWx2Ge016c/pIST7axMk+zCTTEW0MirEGxOn34OBsFhWPVAY+YQsuUVHLmJRM0CKzcC3gigJp1QroPVOme7A7cYjNd+hHOcYMMhQFTTBVSMYzJeB+mCGkM6nEyUhSMRCr++bPqN8qWW96A==
    username: AgB9Fw+g62WpfHjDmo80vfw4tFC6s5ljzZnGQ0zkbVmMlFHh5VmU1tzKf8H5CNAcMSc+m92KC7NrLcBvZ0RRNpcqaHG+rbTo/a9it8KjFro092JA6Qr7nf5NCavhoDrAjP/RHjZRJwiP2aA5gDJpEjZsRywooe8wsWLqDD3P5C2sxxaJNzrK02m02csjBWNezCGpaiHZAYBrkuyz9nExWA848/6nPy2Srd1sgDJ0L6NLBDs3NoLH6pMG3wSSG/PuzEeM4BqvHKtg2Mr+rvVDfeyroGVFBsP1I6R3idC42OOqw5RIywlrMMXSDkNcc1e/1FpMmDaPiv+1Z5kU3v0zSv5lJVlO9EJQiLR4dHHn9G46+/82R60PhBPg2FFyFC/HAm59brUCUyrG/oPK0JS71DYBg9WqWv7yn+R/2kXrHUPbRfVGw0fFY0WLzYiWUcZEAwZo4Z2zTkTOZkB0fmcI8NEfVLULy5Hzp8Ge2E4qwZelKjzR025VuD/Pe4/EycHgRCCXZWFu7Rsd4TZlezk/Tez6oFAkMY29H1a0szrzNA26DWNhHJWY4MBoSG6QzAYlczIS17OGVkuK1jMVVbzRN3nmNVAvHZJSM3tqNE1AmtWFG8L8krNMEge/oF6CpdJupgtOTQd7YW+lb9XGMIUTSHX3ZiLH06M3uCNKUJWzkbKHFuyjUpyujew4Y+YohIe/ydkt2YZOdkVAYQ==
  template:
    metadata:
      name: jupyter-auth
      namespace: jupyter
