---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-secret
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgAx+oabB9LmqrF47Za+z2WwLhm6eM0d8VhLeZoSNQ3wDcTEV/1qnLFh8R5ynnfWoyijk7BDZYssvtH0dGdre0J4SYadhHIEdSTIeGdYMnpZjlmw3Z6ZLB2XegYkoy83jEPS7gGkHPY9p1grI21mbSbTA94peESbi3Ks51TuhhLu8bNPdtYB/h63EmlDdor5RhKa14sp0b/2++HpdYnQZ8stIj57ANyROTVs1ZmhiI+DMdfA8dzU6Dj3gCbkTgoGYCLoGmR/C7I54L3XiA+Ygrign2yqui14whB8zHLAZkuMTrHzo8PXaSnN95xtBdMEZkl0RCkv/ohPrjksg/sEW85aYCU16/tzlqwwNVnqbneYwl0QUXjS/0UJVmNg3kolOZbQnfmU09h10R11upzlZbdSKPTpsPg1cCHMLnLOTUtOBrKEyZZu+u0pFSe24YRqIkgKIBSTzzxO06S/FHFksK0dWMZeg1WHV9p1NSMwGFeU0W5FYdtCIjgDvOFAOlaUSAUAzKNeiYMyfKwsyqHGS1o+pkS6TabVSBb7Qs9+i3VpBFbiKj7eqS4mt18idEDSIR2cvIuCgFyext4BRgmxu9/OAjlyqVDpUvPovHns8r+YjSdt/C5J5DTiZbmn+wnK1MDocr49aEnLyCpJi7SMzTs2h76TSbGL9JjBSZHEZfLnRgTDS40f6Qb6R42esPpxdAM4CnBkkL1DKVOK8+F0k9zgLODA
    RUSTFS_SECRET_KEY: AgBeBv0Z2BmEW+D8EdU4bl39+8AG4ZMek9mj2n1QXeadul2zypwtX5bo5YWq2fTEHCRImEqQ6iNagBngfufWXkbEZNQe3rd3lYk6nCdXoMDBSVbVGUEKaJ+Zh1jTW7tU93IDElJ6uS42fe72XcP5mEDOUnAx3kgApQB5cFe0y1Q0xHPSsIy6tM5d/pzCRHVwSknpdkWfLBjJnRxRwNhifCs5dsKWhG7IBfUUXmC7gszKoHzmfYCvhn7VymmsIXwkyS1iW24DvoB0HUM2Vmoj0u0I/iQUYJB+ndj7qP6rqzkweA/D90QU//Jacgh1oddS24LI1V5e+cnIMUpK9beoaJTt6MuIDABKE62AZVNtXZgIsqt0D+50V2WP3MnO9UzMG5JoFjcSAAIfAAfUVfFSVlwfHkWNjINOdjHgdnQ737uhvlT4A6WfhJVSCY1W1K+z+Vrk9NRW+WknHyBpqVAi93ygIsf8sGo+LEatzaSuI+Jk5yamn9p+TNPRje/L9DiI7KOgPI9+3E1TvUpNFKek3zU7LL2RjH4gJak3hRUPxjwf3Dmr8voI14BxhsGKrRhfxyiTxRxYqMK5IBclUa5FCa/J7PXai2GsbCtPyBCJwW9qXO073LEA9n1wWg8lsum3PBBlgAaZ2HB92WUHODSLHmyXcHSOguS/H81JVEh0NNCJJUG3JjbJmn4Cn9Iz3C7mGb4vUMmpK0XCyWEpE4F2YrZh74Q1gyT543EqbpACXLG7UqEGhh4OTY+e
  template:
    metadata:
      name: rustfs-secret
      namespace: rustfs
    type: Opaque
