---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rustfs-secret
  namespace: rustfs
spec:
  encryptedData:
    RUSTFS_ACCESS_KEY: AgCmvTw2WWbv4Z60L+XCR0QPlog81VsyUe43UEehjxuu7Q1YlqKUMJaVlf9esxhZgURSIACEXQ5rA+O5KzfHpd0AsDu6llqPCkzb3LEcJpQukXg7uot/JJHsf0x9DC2N1Yc6lblQiZE8OOcxWTaOA2u/BVhb5iUhOZOs8aTaM4XRUwVaUL2WpeGoE+QjMlNbt4O7Hgnp0JvqfkjxV2T0dxvoXkB7O3HK/CpsToRBjiS1+QM7vM6P5OsmSH9j/oBjmOz6Gw4IMoY/Z3hmt340kdvmWLu5tcwhrInfiOH4zmutG2tSNVqLV/lx/l9tY4iIjRtD16/pu4zgDP7LTrbQHfgqI7ovKKIama/HaKL+EBxbYtDT1nhNj2/FeKrgH3zOqgHLhXQ/O4yblzDA9etSJCR2XXQIs/15ORgYg45HtwZouTZXaoNeWAhydmRbxvYOF3rzeHmaBoelAcLiUssKF2MbAR4GM4DFhvLAma7U8RqCYOUphL7F4+/Th+agw1m+YefzrBhwHIJlL97B+tOOUF0Mtkz/6zXcTPblm6sP4p1EVrt6OzSqYxh40bRceaZh6jMrESIRwLUoN1n6b8hKjXMpaukd3rP734XdsuVOuTh7dmqwm2Exo18j6/u2vg85bbZ7QWZlL9r6xpDGSz0w0SNzfttsjRXVZFGdYIuQ/7O3uINhN/vpeCnTCcWtTvXhw/sb9PePYw==
    RUSTFS_SECRET_KEY: AgB1pDVO3v9EudQUyqBrn+fKrnZnFPkkrgec77gSSJQbKwGS4b+RgciFJ7FAnyq0tNz8ngEuJgGv5LjFxdPw07nsLb7Dyhzfq3vCOOKOvFVxqOuPAxFtOk/KbhDmZ7Bn2fSdOEyAk/8dhfU8sZOdYtvutdUaIFHQRiMn68Nk6ApvUFlVKXk2f+89h1RYwTKtVZ3MJYAZzUdXWOKewaUJOY1TyWy8Uht5mIGRF6qWfBCoV2HbsZLh8b6O44dg3yw4vpsH5wODVQtTxW+EDaHOJUcOKGphjyfdpYc07CeHcJg14kveZ9Su4zDj+2iHm4pM0W4bcHUdITl11G7HWQ9fJsnvI2hm30wjV9neMcHJVj1R3ReLeutliC5SoQQMfh1WxefnrzbNQ7wRwcfZa75aNRTq/ATsVevCpqPiAIkUDNjNMr7WIeco5/KNrzh5Mda/Pi078LgP8wwnLKsTWzO1D7NVTBLjsrvRSw1gWp3krwhCXAGQ0hIwjL395Vz1BvuVyffmIqxVGSsZ61jnC1A+NxmJq4TSn1dMCmdLWnuY9+LgqQy1K2xiHTe2AgOQbrCQjeAn6fEfYimxIGYmfW1+zCsHtSyogNQG40j86+KsWOmetNka1jwWCLWW67FtTQ8Pf8zCR7DlVD8nh5UP8h+z0bNBOQPy4hOY8rFNhTDm4m6uLj9jRsZvJ+h0xn/z5Tc1JJoWNDe3s/LrxaSzo316AOuHHmM3CrzJrFCvwUXhd17g/Dycs6H3pt+X
  template:
    metadata:
      name: rustfs-secret
      namespace: rustfs
    type: Opaque
