---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: esphome-fleet-secret
  namespace: esphome
spec:
  encryptedData:
    SERVER_TOKEN: AgBI3gnSpNII8VFp5fhkMEheG0pWgRabRTNnq6vg0nPUfM2rxf15I022G3VmfEQlVDoc3EzqdDqyf+s8ocCfRlVmoxkxexqTYaCz0PI8Mb7zGgGCVKRq+i3AthjiSxZUYttGEGOYiID1+ybAAYfbffCbctlw1+TiYbQtzLyec2Xh5zmaEOA+2DlIoMKzhgxCjhqWaSwNBSS92VZsPWoyopihw3t3hf5pZnSyKKAjtJnyuA8pd5w/wSIpK/PdBAWkdd6QlG9G5JYu2dAHopfPzsRDBAAIjBO6rPLp3xZvpy6/bWVN6S6ome6aLYKXGM3UTa5P/GLBnKEAl3WV1gKbwXQ8RcjS++M/8fM9gQmCBzSznP1G1Cy1cBjnDe66rhr/ILkF5krbtMZsL3ajt7f/ULGmzJWtU1I1XLzbFsk3FlWb3rI7Eu6Tv85mhf7BjypMSFtqA/UbTUXeJIoPwoUAjPRGmwh8VPUKx8ueoQDYIQOEfZdpkmnbbBVso0XxcGigWGIwTT8e89Ldj6zWbqPvHo/5IegXAgpADNntgbEEEv4rKqHnV9lwtGEXw5rJMxDLqB97CtONB1j6Ofev5n0C/eykhRE4F3noXu+qoEhTTX2ohYrvNTl774MXVPCJ3UuZixdHbn1aT6F+S46awOFKlP2X/C20nZVWHaw4R+dGiP5+B9bVH2hBkYMAtmrysY2FID6VMubVLBsABHFdzwA7NPgy9A7t+4oyaHjC1Ay6WtJQhY0r0DmFcTkdeeYjSjCtB5PproM6/WYRM4WuHQoibxgqZg==
  template:
    metadata:
      creationTimestamp: null
      name: esphome-fleet-secret
      namespace: esphome
    type: Opaque
