# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - deployment.yaml
  - ingress-route.yaml
  - service.yaml

helmCharts:
  - name: kopiur-pvc
    repo: oci://ghcr.io/csobrinho/helm-charts
    releaseName: mqtt-explorer-kopiur
    namespace: tools
    version: 0.1.0
    valuesInline:
      # yaml-language-server: $schema=https://raw.githubusercontent.com/csobrinho/helm-charts/refs/heads/main/charts/kopiur-pvc/values.schema.json
      uid: 568
      gid: 568
      persistence:
        mqtt-explorer-config:
          retain: true
          accessMode: ReadWriteOnce
          size: 64Mi
          storageClass: local-data
