---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCSRP0ekUzZCzdJJ9M8uvzsTLU6ZHCwyr+aP1i/zWUk2KofSJ/dLURKaZpBQcuOAonDbugcZ8OwUrD6ZPv9V0LbovpIIQ2j4xaFkIFtedFzIgPvxmRVPXFVzo4URGNBY7ZzUcQQB3de9uTselMFoia0kquEC7NM6d2/AiwTDoT36SWP+BMsSOyj5sTWwwpBvWbQ8LBdCarx60e0ZZHX2yP9fHnwYbODed/PpHeIBNdcz8EbB4HwKknj7TAfP1XfZbFX+YCogylXysLjYK3Kq117HFqKhSU33G7FkGzN6Dqz6dvkXVa9ISA/k/Llq1wol1JosBZ9yPNL30LihCacznt6PwLRUlEIejF80sQORl0Zq5gpyeWxPzBp1vijMXD/FPdN19+t29n08jZQR7KPA43ZS2Y1S/KMXbKmIni2qQE+2qGe1S+FHTn80C6ENZe4Sa4fasVNr2Gzu2UoQuAej3XuQpjRlNSx2IgC+JDvH/QTatwRFHeUqsyXiUdUGZYKH3U6llqxXOniwvaHGR2P7w5cpJpORpq7mILHOCdD4VUAKCzNBRw7Dc5Tq0UzMRHreClznzi2h/F4pDVA4GcUbqCjF3De/UwntHoAC1HLSleRmqLdPfMYaXVH1+MBOkZon0nmNzkvfnS4d4N4d4O+3PuydSM3DJwcK6nAJAdI/FmrVqEwAvrc1O2U3yMb+8rdij65bzae5shI8guS7pmvVtYPx5XatllgRRi7853A7fNk7CiQZ1rkB1bl
  template:
    metadata:
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
