apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipmi-server
  namespace: tools
spec:
  selector:
    matchLabels:
      app: ipmi-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ipmi-server
    spec:
      restartPolicy: Always
      containers:
        - name: ipmi-server
          image: mneveroff/ipmi-server:1.2.7
          resources:
            requests:
              cpu: 50m
            limits:
              memory: 256Mi
          ports:
            - containerPort: 80
              name: main
              protocol: TCP
          env:
            - name: TZ
              value: America/Los_Angeles
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 568
            runAsNonRoot: true
            runAsUser: 568
            seccompProfile:
              type: RuntimeDefault
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 568
