keys:
  - &primary age1f0ljhf3prpuyvzghavm3nfh8yzszjc345j7jemcyaprqweplfumsapgv4e
  - &recovery age15aa0shf806u5zzzz77jz5uaqs3k09785lsxf8f0whju6x4uaeahscj6dlp

creation_rules:
  - path_regex: talos/secrets\.yaml$
    key_groups:
      - age: [*primary, *recovery]

  - path_regex: kubernetes/.*\.sops\.yaml$
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    key_groups:
      - age: [*primary, *recovery]

  - path_regex: .*\.sops\.(yaml|json|env)$
    key_groups:
      - age: [*primary, *recovery]
