---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nut-exporter-secret
  namespace: o11y
spec:
  encryptedData:
    NUT_EXPORTER_PASSWORD: AgCCpG2cderKKat5mVPezBuT5JMRAGalAiiSQA1cuurbgleh1mTkD7MuQkYmzgwz5xiX5Mbws5eGMBCdK8tu26uGQmqElozgWpvVcFhwc3glpMQTw+9d5FWnMuD0tjyQp4iPVyQ1WOJq39uYRJnv421sMQYNOuqON2PB0f/GkoXM+c0T+Ytb+0BHfTYPHYYCsUuL3WkfbK7ux2XEQDfESTPYfuXUVqWfvR//71Th2dXSwhjT1bwUc5qpdtW5wilHMoehXbOmVFhVOyWVwU88u0wQ5+Rb5Jmkto/z4NeqlNaVbJToT08S6sNEG2dVKNEg7o0KPbpJ/kphQ2Gxy7Bd2xln30haYNHAvegdoqOTsfAPLsMSYQfy1uAX4FPI7NjW952LasrCSNXp1rJVdAzHX2m8CB4Pl2JV+qgDifuK0RVaVZv+hPRZY6e+qTbUuvaAWu4+9iMo0sdC+JhKEQSHOSjd9yYNaaOM/THQEOQuOzFq+pjoXSvfnoaTpNFNkURDRCEPiqQ/MthOYfw7NVoub9N4sBZJAYhXZD5FE6oh7c0ka3PwyOeihuC8DK868WG5dgm/upLCPoAV95CBZ8WImGlSVaznXHfNbpEv7wK0eUT7jaWYUQQ1pvUB/cUx0NenFtC2zrLMDlfZ/VxyCD2+9IcPKdpPmAuhMXjxCWLbZqD8SWddje3shal/W4lhYBpRHsLIlnuv/QwOQV2RjBzj5iIp+H5asrK36wWEMZmqN+W2JA==
  template:
    metadata:
      name: nut-exporter-secret
      namespace: o11y
