---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dispatcharr-secret
  namespace: media
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCTzZu/JlglzcXtXzTgJIobCG6SBHeoL9P9wQnYeGmH7JOrAEryUbd0ADGmEvSOv9ft4s5ZeZG7/76giwAkZUp9vNzuXukJmuIohrS6rPHC3PB+785gLBNeuZmKzYfYE5u/AaIQ2XSNeBSGEVMANBd75v6h2RkFtrhEM368e1W5KITiB0it4aQBxM4oN1zqF6E4ozbDwLkpha+SZ943IGWM/MNja+luXOS7Iw1DZ8uCgMZeVSVHEyqFMsft/GtYYEHFegfNb806zqpHXaCRC43pZssph7/H+79bFxGtbg7r7Xa35ye5RtYAT8QcXyrPX0ic4AwdJO2pW80WOLv3qVRZqL/F2TdxDqRLXndNrQkHZ4ObSE91gQAD7e8jNl+QrkttN56GCXPPiTX1Zd2uWi5AQ84JjM1E9HPCIlrCpLBwNU5nuqY/s88Z1t8D4nxERxphJeMQZ/lL5Zp7vuRU3rDIeTTbmb/SZQo1qB8+js82FrALdtspc2+48AdUfivbetu6Dd2/SWXLss09MCc8Zyz5eU8S8q01tk9qzDvkDEcpHaX0smJ4OteVfPDAdY5nfqTEW/zb5yAC6CD9fSVP9lX2IQN+wyLamav2cPEzhpQA/f1OJDGMycz/i5OqW3+yr44R+FKsKER+YUQfRq2wJcIdaVX6NNs3GSEYYisb4xwEn2ZWpKRNJ4Cin71D05Kfqympfkaq1LaC9aIKH1+9+jY6tlgMVZ9GZqtaTb+aPQQ=
    SECRET_KEY: AgDJpe96482KWOV7i1Z885RdZjfrSuPG5ZEWcpQERgm5Pl/XA9avoWj+bcBQSikG1ORWxqpSbDNe+B29Gvg0maiqtYjlXaAlpje6Pv0oo/1VGgA4Ou+JFh+mjxc+EvRAN8fQNWl+yt7QHY7R4QAlYgWLT/XtQI7spbVNAARB1EIwrTl5t/JxjJlxsOkbfvDnLZLBwIQtfJdUQBJ3orsBGJm6csel7yuTfB2Pxfe6qBA+a5qFtS1EIhh2vOTC55UlXFTi8m03b5cy/YkkPo27FKqI4SJIJVK/xPmnD0kbYkCQxYWR2XsNTJ4pBe5IqhivxkFzeAp/zZnNyo1SBLuhNZHNlHID4J2nFzq0SmddbnuFcDuO0QXZUY+mvoDyi2m99StlibWX+VxVBtShcYJ8jY8T0ylxL08bhXeGlaag4Ri8bPQ8IdbCu/hHMw+dZK9iA5buZ/VStsy1LUVDd7Wce4f4gbfWHQobtxfe+HfRvr8b6tTyL1shHiNsRRmo/ffxIgohwr7/bQiwYbGLdMOAhMEpMUXcwjXJZxiR3CCVChbDXvcquJnSnddUqGJO2MfdFraoWoKCgh9cKxUoJBNc1/EYlh+UN4pBNWkeCbqPXiX/eF20yr7Uui5xujfQ8pEfMEb4Ft4uBFgRlq8Vrv6wKV7OzbmYsSpDPvld8L4lzSEV6Ace6P88/NHhRV0LOipwaLXi8hdlWQ+YMCF2KeE5u26u/wZk7JUELbcY7Sb40IR5kNISgVjpOHhNbp406FaeTO0/CemTNpuZ4uGZJd6XTXBAiEJZlLUcg4LOBEVXVcDpRceJyjHPhw==
  template:
    metadata:
      creationTimestamp: null
      name: dispatcharr-secret
      namespace: media
    type: Opaque
