---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dispatcharr-secret
  namespace: media
spec:
  encryptedData:
    SECRET_KEY: AgABgyA2Z88E2bNWEWMKaPGi4rWzXzS+8vf48TaPxerb5rfmigu9+38+AsVnrquBadHHbsaZ29stbKh1bVGpO0XlxWGe8zEbrv8sQd6b/IIFrnNDbHO0PW9v6JHNvghfFOxOWwX0X0BG0r79il7qKmA/JNYRxZqiStv9yMIohe3NOuv8TAAd9gYouR7hbVV/FlcclpgmaywqRg/AeHSlza5wkJHZRV/6Zf/Q+unVK8l38oLCRD90Xx/XkiV6nJXsNQEwzqZZ+j+hxtmPbMkLLAIL+t9J3TPpykwNV2BG+n3zo2fvmmHlyrkS+f9w5tb78pM517vg2RhuTLktPbsRExBdNbwvwYg4pLsiY79AyJqjQbsNfneSTdNutCLH+F/xHsYnZTiQTrUotzbjZ5KAVQkElN+uhjbvr4sNCJ0Q5xyf3vkS0Dn+OZD7MEMj5ydtQB1GvCxgrwzb6B0QAq5DiRQ309D53O6CIEJHVGYnNMueNkNA3S/n01bawpTUPCNORoOTZHQFKqikwqVhqUgvEsSd0j2IcKzw+lXEd7ji5lNLaGmNJ8MVrc3DYtZpxHHcKJKwVbF2oUc6JdXHklbCw7HIhXO6e3kkam3ddWuUpf77+av7z5RSj2gGhAS21gkZzTJls0RhbipkUByK2P6xgBu+VV1do+dXY2GyQUB+5gS27LUM8ePlALBTGIrkSRNxvh3WyNprAtrF4HzM64E0mnmEIM3Xr2wagqsLL6x1aYYSecjF18d/8/jpjUtdtj8mwtyjdPkeSyqf2KlE2Zx1lYvxFUQRVBNvZ4IEF4QHyuAiflLRWigQOQ==
  template:
    metadata:
      creationTimestamp: null
      name: dispatcharr-secret
      namespace: media
    type: Opaque
