---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-s3-secret
  namespace: cnpg-system
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBEVv1M34dQct4y7PCurphLB18Y0QdaNsBj/HfXkIVvZXtHjXAG2Zsr7+aoVLkDlEauFAswuG28i4/f4EWy2y4kyywjGD0deT9bYpeqj+dflMT0kZfegHWovbh4TrrflNM1mcMVfSGXJMCIqgGXN9VRjXTJhHSeSqBUzJOxgsx6qXJ4QIEcCnFx3mk4T0uYtvUOEVQKXDyuES5TNYYtDg1O0+ENNhVrFoPPgDv04/tg1nbIqMy/CF4PoqU7AVWEgLu2comX9wUjVqL2Xupu8NTEcp+gZWZ6zDBLKCLBuPyPyksKiquzevQNnMrCJco7ubz6vNbu/3XgDNhoIVU8rPM1EDKngJJeAJn3JlRYRN8rcxuZuhgRNUnjeBP6bxAe/naC9tg6hW4d/sE/bVFAAu6tt2oWrn3Nub4um4oD+ENOBTF0FyZqtBWKPp6VavK7LnuMOgYc/m8HI2U7wJRRAluEefEqMCnIWtI7mEt7GeNqL7G13+tYmxQ/npI9sL8YiPsww576EKowTGjqqBOhvDbn4kl+OOndCKRQj7RlxSm0BCoZkPky7rEhYQ3uBBGxuWUy7XWBdss6e6ZU7999dYqAob5pBMfWSh9kWpVAOr8IPxCdaLiDDlxlP5d3FotxjSW23yDBcI8KnxO58jG3xN8RyzIur42VJtEfl36FW7jF3fUsfReVGvNn+FA8ClqvVHQTLrDs
    ACCESS_SECRET_KEY: AgBhbgvuV1lbvTmJzf25lISxVEfwGeV0qs46OtgqofJ3WA/kYGxDtiWLNlFZ0L72EI6pqvU1Zpecus1bna/LqNvK6vFKjKxuHuMhD3LSYDuTYcsSWORrvGspA/2I7pCH4I2fGiiLKPg/kbmWz8uKwI2k4BU4Flqa7k4DjjjcTdDQwmyiiDHKz5B7w3mcG2vlqtPqboRxeKReX3IYux0eyVLrgEGtFVLBOUv3auUSkLngTux5mR9sxOTFjlI8wA90xecQRB4Y6rREUYjovepTcTirNRJp+toC5gOZCtjKc5KdqsGwHcO0Q1S4kb0dkKoKgQLYwBhN74ugpL0CvnQhtLnsG55scROqxkK8kVf486XMqbmTbbs6gtnpBXtX085kdZtwEowVcBuVVEA9aIlSDERez+US1YLs5wNG9FQhubTu8gMibPjS01JQ/FXFieRLhhWGojXYh0xdb0IB7aDHur/0o3lH0QoT9SgHbhxn5iuq6CvKuu9Zcj6PV+3ZNdkPwJ06vYXKnqWEaqQsJR68ROjcSy8OQkORO9u0j5HXpGKI9ppEzDKM5qQKBpT8s23Gr+E92cXAARMVvek7rlXx+V5SyFIxvD90ZwoPzn8a73MBJeJbTxU1xFzn6ZiipU8g/CROhIkWDD+njL3YRw+oMqWGD2Mym+zAMtzt5VNXY+8mXcvvIL1jknHSLVde09jY3gIZKn8cVSTAY+gnNaYWSoc=
  template:
    metadata:
      name: cnpg-s3-secret
      namespace: cnpg-system
    type: Opaque
