---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dispatcharr-secret
  namespace: cnpg-system
spec:
  encryptedData:
    password: AgCVrmK5vx8lqkZcF0OUPzyloZ+99s8VhulX+XVy4K5HY/ixa9CownXDo18Wy07ufgDswBpqAYFbM096NujBusoYmsxYbyaahryES0d4Iq7HMPqZqo1AJZCatDEqgIU0BBQl0RJB29udkYvTM2CzOdj0MUE54hwM2CUrkNmCHFcBoIbzyWIuWB3fqeo+MRQ4QJKeIkO6Q0z24H6Ep9oUcGXJxvbso2CtwIt1eMXgC5xuA/JcwdL+rursSTj4586vlcaXvzYYthq6p3YtaV1QdAUTQfwC2omcpRoLYfyetdFdtc3g3B55kIbtsIwdOJ3g1gtmMuKc6zOTp4287mhYMml9aUYXOD1y1449m1scRDloAOX2rVCeY9lVL+P70FFTzAopmlZi1zRj3YbYXX+q7e2bGvAmf6adJOFIrbEkXrmnIG+h991CdgowUhMjMAfo6rG/Sioa9yD9DNmTVI+ZuiEF7tRgraguaK8jz4vFuB3KGoS8BO0tKETKZpy/qJoJAaLoG+sKPxlJFB16p5Q6ZbTTPdQzHMSB5Ip7xUJ1SmjU+pHfmaRrBMI1Hhi/ja1IrhcRrjB43ckRwRaUEPlHNTk/GyQU02ytcl4qmHsIQ2jonzYvtAK1Apr806N4+SGc4s6lHX/WKpWbWBqZZhrPJ/ELX1czTbgpkCe0TbsNHR92PsmktWlPexNgvACkw5nnrzAblAcnhVLlEaFDCwXn5nM68JQmXcaw9cusfgemsyQ=
    username: AgCBAqOVLHawitLkIDNJKP36I2EvBGTpjiPTeNCfVKTQkcjNhs6YJyWkCTzF/DS9fW3mjym6H7Bh0nlRl4aU6xoPjP2/JP3y1KNNppFW5w68PFwjouWUHeODJgxYDv5eKLNfc95/W0cGjy99Ayp0otrDZZCIkqEFCICACkoWO9ZogXXGOIN7GqIui/qLtAEth5Gz+f15gnHxp1qPgi/jF7ys9xCL/oFPIZSpth0wMEt5cj7x1zN1QVHzm+0HXYSvJUPzncaeqXBRtHjkvM6LA+22byfJNQUHJdRQTYA5i6WQG+paEnP6O4Xgr+9JoaJQST1xg1J6ByUbrPba8QdvMXk9sORqZ6g1BjXQB9OSSrSbUEhK9QXG91+B2LRrBcHqbKc2jYxIgnAlB8Ee8kF096Ufp97GX0km2UBnlxc7OfQs+73FgP2HxH+u0IMTw6ST5z36tC6PyX2ooYUoEt4/Sj9hCVGgFVEz6gPe92T5HXPfqyI3XvnOjc1vff+/j1SPv2/ng6bDk7mrdfyRw5ENKJt1JFShleTH/V/uQ4urWA1WVD/LV7Mg0jfGniqchDQl3lGzjY8CcDepXxNKgYE1ZirBYZ6YN9MZnFU0Mr5uwadOr4FFLfj3rHLPBIFfMl8zFqFzXSbCxC1LWm2sAANG9M3jf8wS2lAqkAg6/kYGlOwxNoJTC1XNelz7p1vSS7X+r4cT7UIgsCcOT6Q8BQ==
  template:
    metadata:
      creationTimestamp: null
      name: dispatcharr-secret
      namespace: cnpg-system
    type: Opaque
