---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: windmill-secret
  namespace: cnpg-system
spec:
  encryptedData:
    password: AgBZj9lNRVDL7HSx12+jO+3Eqy7Ts+dNW7mjLJDZf3XP0tHnZXMlcZjCk5Z34JrRxP9S56Z0Lgz32k6nt7/scsRBNODZZirwAO9tsMzM+qeY9X2d8+lndlx6/OAQheB3QfHsUS77V8rHB7kCaiBClXH8YxIItimI3tW38kmbi9qm31jLJ5zCETqTWHa9q8jR17wclELpB8+0Jw3vsQgAChXf0A1g2MNu4TAkD64WzqDRRyHaFcUWLcnH7Ng0KX32hrWZ1qfC6rV4N69MBLPjxxKWKeu+XYI1CZ8bv75AXStH+fc8KvGHIG/MMm8B4WylpQ2OsYB4bb1OtK91irU8tNijeH1naovBXPkQCddjkxIjov0meyjYrifnA0x1kst53CdNkw7+VuXF3Qb6c3zQxBFXcU1ORYocI/R4fFiwkunfWvsZGMq2d3rN9vqFY0YvkqQfIN3BnYbS/yrzTsxMtNwRffrStdfjj81ho+YgfD3+HcmHvS9E4Uqh2bE9M5ZkzDwSeUwBnJWTNQ8P4AuokbQ1PQqQdaEtt7blNeL3rbHcx1J6DkkT2nIvsDNYY6Fs4ih/56inPEPEG5HQLJlIOxs966bxv1hbG7PtZJ0e1dgu4LRD7BauCK2IutPGsLyPxFXhIM8GtE2sS9LQGKIqFdQBiLDuPyg21H8go34i+aRCAkKiLoEBHIXkwFd+iqEQJV+1nO/L3emLwqOL88oYLLXxIRExT77iIylvfAN4TqE=
    username: AgB9MBIPO3guyTidN/DGF5XE/54YxPLpWEUagIVQNYTKfl6YCTwtNHHUOT5pWITNuz5GFGbB5Q5CdNhIdTltC/Bj8YT0Mz+eCBs68T6U0d+GLSuGZM+br97tvgAZ/0kkKGCyeIV3JWNsEB6eYKOBksTVgYoJJac++JJSZiQ998rw7MyfrN9flaNHd1RD7/lYeuScR27xfVjR/E0s56Yl4WDO3VVIifUCU+0iwlXKQXhkbdV0plmil/sV3GOh/KWkzUh93Ks4QDys1Rd1HO6dQitDklhPrsqNrsQCbWXVYl+0FX9XuDSTUpRW3Ne0xxbCEnE6SQ4AYoB1+nMena1mbGRI7DO41s2tPXEvhMhRF4ELE0A0RLc5wEosPuonFCjL5+LzlAMtzhMHvC3ZNoPf0cfJGxS45cnF+G5Rpg0fvpZ1wj+c6+viPnJZ2q7NsXtU2553/O6gvp/N7TqLr0lZpCGjralkL4LiU+mETMcvmHtGLwwhOCFN4hOjZSEVtb98T2dTQgdrUILIGOceL8zXbCXNT7Y2gmwQ+zJRloTzjYbbuIi96o1wbEKxfmwKbuGTz3e+I/0n4eonbzyJP6kVmjx6pJCkVEM1ws+m92SI7f+I5EiwW4ehlTdVdaMk/K+pbD0r0PwoFMwyQU1mtnlW38yV54f/nCwBRcluUacro4xKG5U/m8vZ8JylUpRbw1Two7xFf4d6rvI6Lw==
  template:
    metadata:
      creationTimestamp: null
      name: windmill-secret
      namespace: cnpg-system
    type: Opaque
