apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
spec:
  replicas: 0
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: chrome
          image: ghcr.io/browserless/chrome:v2.48.3@sha256:28323ea43f00a15694d554d67aaea6ba92fe3e8039d6a65f77f5b9b738d1548c
          ports:
            - containerPort: 3000
          env:
            - name: SCREEN_WIDTH
              value: "1920"
            - name: SCREEN_HEIGHT
              value: "1024"
            - name: SCREEN_DEPTH
              value: "16"
            - name: MAX_CONCURRENT_CHROME_PROCESSES
              value: "10"
            - name: MAX_CONCURRENT_SESSIONS
              value: "5"
            - name: CONNECTION_TIMEOUT
              value: "300000"
            - name: ENABLE_DEBUGGER
              value: "false"
            - name: PREBOOT_CHROME
              value: "true"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              add: null
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: chrome
spec:
  selector:
    app: chrome
  ports:
    - port: 3000
      targetPort: 3000
