apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: chrome
          image: ghcr.io/browserless/chrome:v2.48.0@sha256:d7c2931b77472603d7e16a0626edbb78eee2c9c6e006cd2ada8fe5df2290b11b
          ports:
            - containerPort: 3000
          env:
            - name: SCREEN_WIDTH
              value: "1920"
            - name: SCREEN_HEIGHT
              value: "1024"
            - name: SCREEN_DEPTH
              value: "16"
            - name: MAX_CONCURRENT_CHROME_PROCESSES
              value: "10"
            - name: MAX_CONCURRENT_SESSIONS
              value: "5"
            - name: CONNECTION_TIMEOUT
              value: "300000"
            - name: ENABLE_DEBUGGER
              value: "false"
            - name: PREBOOT_CHROME
              value: "true"
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: chrome
spec:
  selector:
    app: chrome
  ports:
    - port: 3000
      targetPort: 3000
