apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromium
  template:
    metadata:
      labels:
        app: chromium
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: chromium
          image: ghcr.io/browserless/chromium:v2.48.0@sha256:fcb6b9f2c0e9940c025dd07eebf8fb389ec65a26e128489096ee65474f82cd15
          ports:
            - containerPort: 3000
          env:
            - name: SCREEN_WIDTH
              value: "1920"
            - name: SCREEN_HEIGHT
              value: "1024"
            - name: SCREEN_DEPTH
              value: "16"
            - name: MAX_CONCURRENT_SESSIONS
              value: "5"
            - name: CONNECTION_TIMEOUT
              value: "300000"
            - name: ENABLE_DEBUGGER
              value: "false"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            capabilities:
              add: null
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 1000m
---
apiVersion: v1
kind: Service
metadata:
  name: chromium
spec:
  selector:
    app: chromium
  ports:
    - port: 3000
      targetPort: 3000
