# From https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
# From https://github.com/trueforge-org/truecharts/blob/master/charts/stable/changedetection-io/values.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - chrome.yaml
  - chromium.yaml
  - ingress-route.yaml

helmCharts:
  - name: changedetection-io
    repo: oci://oci.trueforge.org/truecharts
    releaseName: changedetection-io
    namespace: tools
    version: 6.1.2
    kubeVersion: "1.33"
    includeCRDs: true
    valuesInline:
      TZ: America/Los_Angeles
      podOptions:
        nodeSelector:
          kubernetes.io/arch: "arm64"
      persistence:
        datastore:
          enabled: true
          mountPath: /datastore
          retain: true
          accessMode: ReadWriteOnce
          size: 8Gi
          storageClass: "ceph-block"
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  WEBDRIVER_URL: "http://chromium:3000/wd/hub"
                  PLAYWRIGHT_DRIVER_URL: "ws://chromium:3000"

