---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-infra-adm
spec:
  blocks:
    - cidr: "10.10.11.20/32"
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: pool-infra-adm
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-infra-dns1
spec:
  blocks:
    - cidr: "10.10.11.22/32"
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: pool-infra-dns1
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-infra-dns2
spec:
  blocks:
    - cidr: "10.10.11.23/32"
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: pool-infra-dns2
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-infra-int-old
spec:
  blocks:
    - cidr: "10.10.11.24/32"
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: pool-infra-int-old
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-infra-ext-old
spec:
  blocks:
    - cidr: "10.10.11.25/32"
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: pool-infra-ext-old
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-infra-apt
spec:
  blocks:
    - cidr: "10.10.11.26/32"
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: pool-infra-apt
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-infra-prometheus
spec:
  blocks:
    - cidr: "10.10.11.27/32"
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: pool-infra-prometheus
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-infra-home-assistant
spec:
  blocks:
    - cidr: "10.10.11.28/32"
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: pool-infra-home-assistant
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumloadbalancerippool_v2.json
apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-infra-plex
spec:
  blocks:
    - cidr: "10.10.11.29/32"
  serviceSelector:
    matchLabels:
      io.cilium/lb-pool: pool-infra-plex
