apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets/supermarket-secret-enc.yaml
  - https://github.com/csobrinho/supermarket-api//prometheus?ref=7205249d1ee50e950859b1f61ba3eef966c769a7

helmCharts:
  - name: supermarket
    releaseName: supermarket
    namespace: tools
    valuesInline:
      image: ghcr.io/csobrinho/supermarket-api:main@sha256:dcc2ac83b6b0690fe35d5114c0b07863f6e0e182682cab15a4cd8409e67c2221
      users:
        - name: sobry
          schedule: "0 * * * *"
        - name: judy
          schedule: "2 * * * *"

helmGlobals:
  chartHome: helm
