apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets/supermarket-secret-enc.yaml
  - https://github.com/csobrinho/supermarket-api//prometheus?ref=7205249d1ee50e950859b1f61ba3eef966c769a7

helmCharts:
  - name: supermarket
    releaseName: supermarket
    namespace: tools
    valuesInline:
      image: ghcr.io/csobrinho/supermarket-api:main@sha256:914f9015f7d25bf80e84921cf8f2813da5b5b0514023656a3fbcd616e35ad3e4
      users:
        - name: sobry
          schedule: "0 * * * *"
        - name: judy
          schedule: "2 * * * *"

helmGlobals:
  chartHome: helm
