# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets/supermarket-secret-enc.yaml
  - https://github.com/csobrinho/supermarket-api//prometheus?ref=7205249d1ee50e950859b1f61ba3eef966c769a7

helmCharts:
  - name: supermarket
    releaseName: supermarket
    namespace: tools
    valuesInline:
      image: ghcr.io/csobrinho/supermarket-api:main@sha256:a4c08a8228a6ed0ab6bdfbdf08096dbd6df03bd267b09f9a2ea3d7e00468c9fd
      users:
        - name: sobry
          schedule: "0 * * * *"
        - name: judy
          schedule: "2 * * * *"

helmGlobals:
  chartHome: helm
