---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: esphome-fleet-secret
  namespace: esphome
spec:
  encryptedData:
    SERVER_TOKEN: AgBsYDI1dThU8R6bmCOjfhJhEMxo0/YZDWVaQd5M7NUsd+l7nmcheZ6zRIB3YF/6aWYTHax5NBxgVSM3yuWOTGMpUrbHojHNKyInbmRRLu/OV6EhUZmzUnNz8JwSEqlLe2f3Rkx9cSs6E9YHkraeHM0Iw+asHXB+mCO6dbL040KlgeYN6ohelC69HKszDLq0nSRo9WE6vWNNjNot/rBomfGe3vCoJc+8yCijCsxrUyzKmTXiFfiH9dwwEVRA3yfAmVarO/hHTNmSfBfmWtDZoFi3Yvi9X6WN4SNFG8u3YpamWr+43+YNvGgwJWE5UYSzJBhoLyJYse3xps5mKeYonLxMUkyVnfgq48msMRjWEXydrB/ky5Alwm/Lg6ujbNSBkFl5Muyj4Lq0ey37l9c/XFxvp2xW7bY2Yt47fxFrshnflWgNfER2JuSmqMOjL476VM+HVu7x/0Tpaiixd5MlYAfX2/8mOyJRHEI/egLScLxda4wHCb4ol/5ob8yPKsT+NUeX1Ugf12lk3i1RqaEvl2lfwkF7DQbQyQxQrNSnuxRbzbbE1ql18j3yINNJiYW1Fs2G9HaMYc/lwtXNEW7zypaU4+d3j+kxUR1/3VQ7WWmlxfjzz/yW0xCf4LA2NnbHk2d8jEQuwOuOVOv4bCyy+HKpPaWOcwj5qbGb28vA8/AvoCsKOG3WrtToMKGax3uR1vFwunxzhQd7+vNie5OJ1CSqcOUGBai7kzFBR7pDWFzvNcfdBbD/dQROslTuc0aogoj3/ePEllTMbp0Vri/zg93O
  template:
    metadata:
      creationTimestamp: null
      name: esphome-fleet-secret
      namespace: esphome
    type: Opaque
