---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-secret
  namespace: csi-proxmox
spec:
  encryptedData:
    config.yaml: AgCPBGolekYT0rDuIRXrn3CFpvBeHs5YethoGMjsMhRPKW/8B7kkEGJHHV0vUZmzvS/eOJvWq2iJ52MdlkygZ6rtHleDCjG6gTikZ242sCDGU0f9bMelWCRyk+Jcq1eSNz0rHGfzQmVBRMOto2VMCKD2mBYrhPNL3rFsfgSOvZ20QiZ9wQtXtsZWOwH8hd6xrv4g9gHaGswNDJdjlzRJ1CfoDVO8NeIywe/5om4lpRD2/5nZ7iOWAgXlpqMhEl1wcksCm89rxIHvQRT6pppW51dWtLXKnEk5Z/SC8zKxfYAD4sNSieCeQRRq/525jF1PjnjzSK/u3aUcCsLHajb6Q1IIqpKWCZ6PgtolswPbpV+YHoGHFM12deAwtUxyUOiB1XWwpmq4cRM1SqTqCOw/9pUeForPmcA9/tJsObfnkAZx0eOrRDiuGctRMlxIX1S2RyOIny7dyJS1zs3oTidaDSUSOHlJIw61sexV1PSHIYh9XwlwBxOi11nmung1+wEX4uiPlvlBP/BYzYqiEcbpa+csDxF7mvCyqGGj4ioAVasTXuwnVgdS9+UoKkCT4gBgPEZAQkT8SiYvR4qJoPYYR3/M9Se5F1oQ2N/Vr+JILS9/gYBfL1gvNvXTHRjMTyo/tZzRZZJpXfNpxxqJKGq+73+QNlAJUYVKLMmycOTgHRS4KqLLg1o4dK3YFHoXzxZtJ3Eqpz/R3spLTAwif6lbUGWF9YN1Lxigd0wJQ2RWNHP2/JvQLzMvlmpzwL8BrB/Hz8EPWLMNyQNcBACkIh/SnnS3SBiaNfL+aJVG0Wa2xh4rLDm0K8QFhg2tpQpL79SWpxecBYw4UkUy665iqTL/tSr1VpEkeVfkZQ0/S8l0WtQ3Bq4qR4XB8Rg/r2Fn3eR7mP63ju8Soy6HUjmkSdNaKEVxUFhVTuj7AXTlbMurT+8DhcDhJ3n6FvX9klmSibJHcrcaHdcn
  template:
    metadata:
      name: proxmox-csi-secret
      namespace: csi-proxmox
    type: Opaque
