# From https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/values.yaml
# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: descheduler
    repo: https://kubernetes-sigs.github.io/descheduler/
    releaseName: descheduler
    namespace: kube-system
    version: 0.36.0
    includeCRDs: true
    valuesInline:
      kind: Deployment
      deschedulingInterval: 2m
      deschedulerPolicyAPIVersion: descheduler/v1alpha2
      deschedulerPolicy:
        metricsProviders:
          - source: KubernetesMetrics
        profiles:
          - name: Default
            pluginConfig:
              - name: DefaultEvictor
                args:
                  podProtections:
                    defaultDisabled:
                      - "PodsWithLocalStorage"
                    # extraEnabled:
                    #   - "PodsWithPVC"
                    # NOT adding PodsWithPVC to keep your persistent storage volumes stable
              - name: RemovePodsHavingTooManyRestarts
                args:
                  podRestartThreshold: 100
                  includingInitContainers: true
              - name: LowNodeUtilization
                args:
                  metricsUtilization:
                    source: KubernetesMetrics
                  thresholds:
                    cpu: 20
                    memory: 40
                    pods: 20
                  targetThresholds:
                    cpu: 50
                    memory: 70
                    pods: 50
              - name: RemovePodsViolatingNodeAffinity
                args:
                  nodeAffinityType:
                    - requiredDuringSchedulingIgnoredDuringExecution
              - name: RemovePodsViolatingNodeTaints
              - name: RemovePodsViolatingInterPodAntiAffinity
              - name: RemovePodsViolatingTopologySpreadConstraint
              - name: RemoveDuplicates
            plugins:
              balance:
                enabled:
                  - RemoveDuplicates
                  - RemovePodsViolatingTopologySpreadConstraint
                  - LowNodeUtilization
              deschedule:
                enabled:
                  - RemovePodsHavingTooManyRestarts
                  - RemovePodsViolatingNodeTaints
                  - RemovePodsViolatingNodeAffinity
                  - RemovePodsViolatingInterPodAntiAffinity
