---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: talos-backup-secrets
  namespace: kube-system
spec:
  roles:
    - os:etcd:backup
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: talos-backup
  namespace: kube-system
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: talos-backup
              image: ghcr.io/siderolabs/talos-backup:latest@sha256:7fc186ff37a3137f470082cb609bf1dc3bcece13dd9a6421ec09cfdf4f33ae6c
              workingDir: /tmp
              imagePullPolicy: IfNotPresent
              env:
                - name: CUSTOM_S3_ENDPOINT
                  value: https://s3.sobrinho.pt
                - name: USE_PATH_STYLE
                  value: "true"
                - name: BUCKET
                  value: etcd
                - name: CLUSTER_NAME
                  value: talos
              envFrom:
                - secretRef:
                    name: s3-etcd-secret
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
              command:
                - /talos-backup
              volumeMounts:
                - mountPath: /tmp
                  name: tmp
                - mountPath: /.talos
                  name: talos
                - mountPath: /var/run/secrets/talos.dev
                  name: talos-secrets
          restartPolicy: OnFailure
          volumes:
            - emptyDir: {}
              name: tmp
            - emptyDir: {}
              name: talos
            - name: talos-secrets
              secret:
                secretName: talos-backup-secrets
