apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: dispatcharr
    app.kubernetes.io/name: dispatcharr
  name: dispatcharr
  namespace: media
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: dispatcharr
      app.kubernetes.io/name: dispatcharr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: dispatcharr
        app.kubernetes.io/name: dispatcharr
    spec:
      nodeSelector:
        kubernetes.io/arch: "amd64"
      containers:
        - name: dispatcharr
          image: ghcr.io/dispatcharr/dispatcharr:0.26.0@sha256:9275b0c1f5319a84b412af6839a1364ef25b61d8d6ff0d2130a6c2b2504a8b07
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              gpu.intel.com/i915: "1"
              cpu: 1000m
              memory: 2Gi
            requests:
              gpu.intel.com/i915: "1"
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 9191
              name: main
              protocol: TCP
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: DISPATCHARR_PORT
              value: $(DISPATCHARR_SERVICE_PORT)
            # - name: DISPATCHARR_ENV
            #   value: modular
            # - name: POSTGRES_HOST
            #   value: "xxx.namespace.svc.cluster.local"
            # - name: POSTGRES_PASSWORD
            #   value: ""
          volumeMounts:
            - mountPath: /data
              name: data
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: main
            timeoutSeconds: 1
          livenessProbe:
            tcpSocket:
              port: main
            failureThreshold: 5
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: main
            timeoutSeconds: 1
      securityContext:
        supplementalGroups:
          - 105 # Add render group.
          - 44
          - 107
          - 568
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: dispatcharr-data
