# From https://github.com/windmill-labs/windmill-helm-charts/blob/main/charts/windmill/values.yaml
# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress-route.yaml
  - postgresql-database.yaml
  - secrets/windmill-secret-enc.yaml

helmCharts:
  - name: windmill
    repo: https://windmill-labs.github.io/windmill-helm-charts/
    releaseName: windmill
    namespace: windmill
    version: 4.0.204
    includeCRDs: true
    valuesInline:
      postgresql:
        enabled: false
      windmill:
        baseDomain: windmill.sobrinho.pt
        baseProtocol: https
        appReplicas: 1
        frontendReplicas: 1
        workerReplicas: 1
        lspReplicas: 1
        databaseUrlSecretName: "windmill-secret"
        databaseUrlSecretKey: url
        app:
          nodeSelector:
            kubernetes.io/arch: "amd64"
        windmillExtra:
          nodeSelector:
            kubernetes.io/arch: "amd64"

      ingress:
        enabled: false
      enterprise:
        enabled: false

# Force amd64 since jemalloc does not support arm64 16k page size.
patches:
  - target:
      kind: Deployment
      name: "windmill-workers-.*"
      labelSelector: "app.kubernetes.io/name=windmill-workers"
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ignored
      spec:
        replicas: 1
        template:
          spec:
            nodeSelector:
              kubernetes.io/arch: "amd64"
