# See https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/values.yaml
# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress-route.yaml
  - secrets/jupyter-auth-enc.yaml

helmCharts:
  - name: jupyterhub
    repo: https://hub.jupyter.org/helm-chart/
    releaseName: jupyter
    namespace: jupyter
    version: 4.4.2
    includeCRDs: true
    valuesInline:
      hub:
        extraEnv:
          TZ: America/Los_Angeles
          JUPYTERHUB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: jupyter-auth
                key: username
          JUPYTERHUB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: jupyter-auth
                key: password
        extraConfig:
          auth.py: |
            import os
            c.Authenticator.allowed_users = {os.environ["JUPYTERHUB_USERNAME"]}
            c.Authenticator.admin_users = {os.environ["JUPYTERHUB_USERNAME"]}
            c.SharedPasswordAuthenticator.admin_password = os.environ["JUPYTERHUB_PASSWORD"]
        db:
          type: other
          url: sqlite:////srv/jupyterhub/jupyterhub.sqlite
          upgrade: true
        extraVolumes:
          - name: jupyter-hub
            persistentVolumeClaim:
              claimName: jupyter-hub
        extraVolumeMounts:
          - name: jupyter-hub
            mountPath: /srv/jupyterhub
        config:
          JupyterHub:
            authenticator_class: shared-password
          IdentityProvider:
            token: ""
      prePuller:
        continuous:
          enabled: false
        hook:
          enabled: false
      proxy:
        service:
          type: ClusterIP
      scheduling:
        userScheduler:
          enabled: false
      singleuser:
        defaultUrl: /lab
        storage:
          type: static
          static:
            pvcName: jupyter-home
            subPath: "" # Single user: the whole volume is the home.

  - name: kopiur-pvc
    repo: oci://ghcr.io/csobrinho/helm-charts
    releaseName: jupyter-kopiur
    namespace: jupyter
    version: 0.1.0
    valuesInline:
      persistence:
        jupyter-home:
          uid: 1000
          gid: 100
          retain: true
          accessMode: ReadWriteOnce
          size: 5Gi
          storageClass: local-data
        jupyter-hub:
          uid: 1000
          gid: 1000
          retain: true
          accessMode: ReadWriteOnce
          size: 1Gi
          storageClass: local-db

components:
  - ../../../../components/managed-sablier
