# From https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
# From https://github.com/trueforge-org/truecharts/blob/master/charts/stable/whatsapp/values.yaml
# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - deployment.yaml
  - ingress-route.yaml
  - pvc.yaml
  - service.yaml
  - secrets/whatsapp-secret-enc.yaml

helmCharts:
  - name: kopiur-pvc
    repo: oci://ghcr.io/csobrinho/helm-charts
    releaseName: whatsapp-kopiur
    namespace: media
    version: 0.1.0
    valuesInline:
      # yaml-language-server: $schema=https://raw.githubusercontent.com/csobrinho/helm-charts/refs/heads/main/charts/kopiur-pvc/values.schema.json
      uid: 568
      gid: 568
      backup:
        schedule:
          cron: "" # Disable the automatic backup schedule.
      persistence:
        whatsapp-media:
          existingClaim: true
        whatsapp-sessions:
          existingClaim: true

components:
  - ../../../../components/disable-revision-history
