---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-password-secret
  namespace: o11y
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgBveobch3USBMnObQREjT2AygqhnWJtLTtY2VofX0/UdnhTemJ8WAyvVvQ/znJG47Yvab/ksesLaMDKvX6ceDG/VeT3a7Oa5WM5g1IMPvgeHdT/j+IyikknHYd/OXgs2LPs0OW627QOiaZ/bxBwicEnAQHkc+gc5X4fkH34CWtFtdXJfBtjGONS1/7GXVyrOOVaaDGyIEGh2v76tLi3fQQg3vdSEqzwGywQz0tYxPPp4eK1zW0aKvM6LsFFFLyZaVxZd+HWBLWNdYwz8G5Lpw5oP/2GtIT1Rrr2rI6tEZQfsdv253C5vKG4vCBrF732ICSA0qxMUls3bQXxGVwhI9okGNbXL7VNA5W8/hl/6bL82gQshMX7Nog9byh34tWcwEXvAoIdF/oVRRkm1SAUFkcwYL5K0RZXYtsO5yKyAphlZZGZTONKy8B1KNBcu6W2y2s7XWIKwH62IFuaIY6W4cLC/GG2HDXolRDqzTNDBPKQcWNGOle9bAQzP3liJrEJCJsZB8qO10hLb7AYBo16zOk35/9jZlK+8zK0tQSi+9IyL348yjlS4Z73KrQOncbCvmszBLFWV7TJP1G74aicmGc/TF/eUPuRi8zuAjl6T3hbbsRu9UHGUtiKayve8zlOAYZ7LhDCjlEhTueGsE/FxxuLXdsGw9UJSvpZ2vDNnsqPZ2UfeFxRPNhQPyViOmor2pNWyuMDVds7eJMu4PGRxpkhy2ijkSMUJbZhZfV1PTtSb92gxW4KX592
  template:
    metadata:
      name: grafana-admin-password-secret
      namespace: o11y
    type: Opaque
