# yaml-language-server: $schema=./values.schema.json
image:
  repository: ghcr.io/weirded/esphome-dist-server
  pullPolicy: IfNotPresent
  tag: "1.7.0@sha256:5181773d77c01e8251622b117c3ba02e3da8137df8940c2d49a5a0331d0720ba"

service:
  main:
    ports:
      main:
        port: 8765
        targetPort: 8765
workload:
  main:
    podSpec:
      hostNetwork: true
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /ui/api/server-info
            readiness:
              type: http
              path: /ui/api/server-info
            startup:
              type: http
              path: /ui/api/server-info
          env:
            HA_MODE: "standalone"
persistence:
  config:
    enabled: true
    mountPath: /config/esphome
    retain: true
    storageClass: "ceph-block"
    accessMode: ReadWriteOnce
    size: 256Mi
  data:
    enabled: true
    mountPath: /data
    retain: true
    storageClass: "ceph-block"
    accessMode: ReadWriteOnce
    size: 8Gi
