# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/traefik.io/ingressroute_v1alpha1.json
kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: strata-ingress
  namespace: llm
  annotations:
    external-dns.kubernetes.io/target: infra-int
spec:
  entryPoints:
    - websecure
    - websecure-ext
  routes:
    - match: Host(`strata.sobrinho.pt`)
      kind: Rule
      services:
        - name: strata
          port: http
  tls:
    secretName: strata-cert
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: strata-cert
  namespace: llm
spec:
  secretName: strata-cert
  dnsNames:
    - strata.sobrinho.pt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
