# From https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
# From https://github.com/trueforge-org/truecharts/blob/master/charts/stable/plex/values.yaml
# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress-route.yaml

helmCharts:
  - name: plex
    repo: oci://oci.trueforge.org/truecharts
    releaseName: plex
    namespace: media
    version: 22.10.6
    includeCRDs: true
    valuesInline:
      TZ: America/Los_Angeles
      service:
        main:
          externalTrafficPolicy: Local
          annotations:
            external-dns.kubernetes.io/hostname: infra-plex
          labels:
            io.cilium/lb-pool: pool-infra-plex
          type: LoadBalancer
      workload:
        main:
          podSpec:
            containers:
              main:
                env:
                  CUDA_DISABLE_PERF_BOOST: "1" # Don't jump to high clocks for NVENC/NVDEC.
                  # NVIDIA CDI mounts cuda drivers in /usr/lib.
                  LD_LIBRARY_PATH: /usr/lib
      persistence:
        config:
          existingClaim: plex-config
        media:
          enabled: true
          type: nfs
          server: infra-vm
          path: /mnt/library
          mountPath: /data
      plex:
        serverIP: 10.10.10.9 # infra-plex VIP.
        additionalAdvertiseURL: "https://plex.sobrinho.pt:443"
      containerOptions:
        NVIDIA_CAPS:
          - video
          - compute
          - utility
      scheduling:
        runtimeClass: nvidia
      podOptions:
        defaultAffinity: false
        tolerations:
          - key: nvidia.com/gpu
            operator: Equal
            value: present
            effect: NoSchedule
      resources:
        requests:
          cpu: 500m
        limits:
          cpu: 0 # Unlimited.
          memory: 8Gi

  - name: kopiur-pvc
    repo: oci://ghcr.io/csobrinho/helm-charts
    releaseName: plex-kopiur
    namespace: media
    version: 0.1.0
    valuesInline:
      uid: 568
      gid: 568
      persistence:
        plex-config:
          enabled: true
          retain: true
          storageClass: local-data
          accessMode: ReadWriteOnce
          size: 16Gi

patches:
  # GPU claim; TrueCharts can't set resourceClaims.
  - patch: |-
      - op: add
        path: /spec/template/spec/resourceClaims
        value:
          - name: transcode-gpu
            resourceClaimName: transcode-gpu
      - op: add
        path: /spec/template/spec/containers/0/resources/claims
        value:
          - name: transcode-gpu
    target:
      group: apps
      version: v1
      kind: Deployment
      name: plex

components:
  - ../../../../components/disable-revision-history
