# From https://bjw-s-labs.github.io/helm-charts/docs/app-template/reference/explorer/
# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress-route.yaml

helmCharts:
  - name: app-template
    repo: oci://ghcr.io/bjw-s-labs/helm
    releaseName: bentopdf
    version: 5.1.0
    namespace: tools
    valuesFile: values-empty.yaml
    valuesInline:
      # yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json
      controllers:
        app:
          revisionHistoryLimit: 0
          containers:
            app:
              image:
                repository: bentopdfteam/bentopdf-simple
                tag: v2.8.8@sha256:3d62b8f8eece5fe947026ac3925ff08fda245b3d6ba2c3916b94da91e0010c74
                pullPolicy: IfNotPresent
              env:
                TZ: America/Los_Angeles
              probes:
                liveness: &probe
                  enabled: true
                  type: HTTP
                  path: /
                  spec:
                    periodSeconds: 30
                    timeoutSeconds: 5
                    failureThreshold: 5
                readiness:
                  <<: *probe
                  spec:
                    periodSeconds: 10
                    timeoutSeconds: 5
                    failureThreshold: 5
                startup:
                  <<: *probe
                  spec:
                    periodSeconds: 5
                    failureThreshold: 60
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  memory: 512Mi
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: { drop: ["ALL"] }
      defaultPodOptions:
        automountServiceAccountToken: false
        enableServiceLinks: false
        securityContext:
          runAsNonRoot: true
          runAsUser: &uid 568
          runAsGroup: *uid
          fsGroup: *uid
          fsGroupChangePolicy: OnRootMismatch
          supplementalGroups: [*uid]
          seccompProfile:
            type: RuntimeDefault
      service:
        app:
          primary: true
          ports:
            http:
              port: 8080
      persistence:
        tmp:
          type: emptyDir
        nginx-run:
          type: emptyDir
          globalMounts:
            - path: /etc/nginx/tmp
        nginx-cache:
          type: emptyDir
          globalMounts:
            - path: /var/cache/nginx

components:
  - ../../../../components/managed-sablier
