# From https://github.com/pajikos/home-assistant-helm-chart/blob/main/charts/home-assistant/values.yaml
# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress-route.yaml

helmCharts:
  - name: home-assistant
    repo: http://pajikos.github.io/home-assistant-helm-chart/
    releaseName: home-assistant
    namespace: home-assistant
    version: 0.3.83
    includeCRDs: true
    valuesInline:
      env:
        - name: TZ
          value: America/Los_Angeles
      service:
        type: LoadBalancer
        port: 8123
        annotations:
          external-dns.alpha.kubernetes.io/hostname: infra-home-assistant
      hostPort:
        enabled: true
        port: 8123
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/arch: arm64
      securityContext:
        privileged: true
      persistence:
        enabled: true
        retain: true
        accessMode: ReadWriteOnce
        size: 12Gi
        storageClass: "ceph-block"
      additionalVolumes:
        - hostPath:
            path: /run/dbus
            type: Directory
          name: dbus
      additionalMounts:
        - mountPath: /run/dbus
          name: dbus
      addons:
        codeserver:
          enabled: true

  - name: kopiur-pvc
    repo: oci://ghcr.io/csobrinho/helm-charts
    releaseName: home-assistant-kopiur
    namespace: home-assistant
    version: 0.1.0
    valuesInline:
      persistence:
        home-assistant-home-assistant-0:
          existingClaim: true
      backup: # Must run as root.
        schedule:
          cron: "" # Disable the automatic backup schedule.
        mover:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          podSecurityContext:
            fsGroup: 0
      populate:
        mover:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          podSecurityContext:
            fsGroup: 0

patches:
  - patch: |-
      - op: add
        path: /spec/volumeClaimTemplates/0/apiVersion
        value: v1
      - op: add
        path: /spec/volumeClaimTemplates/0/kind
        value: PersistentVolumeClaim
      - op: add
        path: /spec/template/spec/containers/1/securityContext/runAsUser
        value: 0
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: home-assistant
  - patch: |-
      - op: add
        path: /metadata/labels/io.cilium~1lb-pool
        value: pool-infra-home-assistant
    target:
      version: v1
      kind: Service
      name: home-assistant
