router bgp 65000
  bgp router-id 10.10.2.1
  bgp log-neighbor-changes
  no bgp ebgp-requires-policy
  !
  neighbor k8s peer-group
  neighbor k8s remote-as 65002
  !
  neighbor 10.10.2.31 peer-group k8s
  neighbor 10.10.2.31 description "infra31 (control)"
  neighbor 10.10.2.32 peer-group k8s
  neighbor 10.10.2.32 description "infra32 (control)"
  neighbor 10.10.2.33 peer-group k8s
  neighbor 10.10.2.33 description "infra33 (control)"
  !
  neighbor 10.10.2.34 peer-group k8s
  neighbor 10.10.2.34 description "infra34 (worker)"
  neighbor 10.10.2.35 peer-group k8s
  neighbor 10.10.2.35 description "infra35 (worker)"
  neighbor 10.10.2.36 peer-group k8s
  neighbor 10.10.2.36 description "infra36 (worker)"
  neighbor 10.10.2.37 peer-group k8s
  neighbor 10.10.2.37 description "infra37 (worker)"
  neighbor 10.10.2.38 peer-group k8s
  neighbor 10.10.2.38 description "infra38 (worker)"
  !
  address-family ipv4 unicast
    redistribute connected
    neighbor k8s next-hop-self
    neighbor k8s soft-reconfiguration inbound
    neighbor k8s route-map ALLOW-ALL in
    neighbor k8s route-map ALLOW-ALL out
    maximum-paths 8
  exit-address-family
exit
route-map ALLOW-ALL permit 10
exit