# From https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
# From https://github.com/trueforge-org/truecharts/blob/master/charts/stable/mosquitto/values.yaml
# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: mosquitto
    repo: oci://oci.trueforge.org/truecharts
    releaseName: mosquitto
    namespace: mosquitto
    version: 18.7.0
    includeCRDs: true
    valuesInline:
      TZ: America/Los_Angeles
      service:
        main:
          externalTrafficPolicy: Local
          annotations:
            external-dns.alpha.kubernetes.io/hostname: infra-mqtt
          labels:
            io.cilium/lb-pool: pool-infra-mqtt
          type: LoadBalancer
        websockets:
          enabled: false
      auth:
        enabled: true
      persistence:
        data:
          existingClaim: mosquitto-data
        configinc:
          existingClaim: mosquitto-configinc
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 0 # No limit.
          memory: 512Mi

  - name: kopiur-pvc
    repo: oci://ghcr.io/csobrinho/helm-charts
    releaseName: mosquitto-kopiur
    namespace: mosquitto
    version: 0.1.0
    valuesInline:
      # yaml-language-server: $schema=https://raw.githubusercontent.com/csobrinho/helm-charts/refs/heads/main/charts/kopiur-pvc/values.schema.json
      uid: 568
      gid: 568
      persistence:
        mosquitto-data:
          retain: true
          storageClass: local-db
          accessMode: ReadWriteOnce
          size: 1Gi
        mosquitto-configinc:
          retain: true
          storageClass: local-data
          accessMode: ReadWriteOnce
          size: 64Mi
