apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
metadata:
  name: disable-revision-history

patches:
  - patch: |
      - op: replace
        path: /spec/revisionHistoryLimit
        value: 0
    target:
      kind: (Deployment|StatefulSet|DaemonSet)
