# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
  namespace: cnpg-system
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.10
  storage:
    size: 16Gi
    storageClass: local-db
  resources:
    requests:
      cpu: 250m
    limits:
      memory: 1536Mi
  enableSuperuserAccess: true
  # REPLICATION: START
  externalClusters:
    - name: cluster-old
      connectionParameters:
        host: infra-pgo
        port: "5432"
        user: streaming_replica
        dbname: postgres
        sslmode: prefer
      sslKey:
        name: cluster-replication-old
        key: tls.key
      sslCert:
        name: cluster-replication-old
        key: tls.crt
  bootstrap:
    pg_basebackup:
      source: cluster-old
  replica:
    enabled: true
    source: cluster-old
  # REPLICATION: END
  managed:
    roles:
      - name: dispatcharr
        passwordSecret:
          name: dispatcharr-secret
        login: true
        connectionLimit: -1
        ensure: present
        inherit: true
      - name: windmill_user
        login: false
        connectionLimit: -1
        ensure: present
        inherit: true
      - name: windmill_admin
        login: false
        connectionLimit: -1
        ensure: present
        inherit: true
        bypassrls: true
        inRoles:
          - windmill_user
      - name: windmill
        passwordSecret:
          name: windmill-secret
        login: true
        connectionLimit: -1
        ensure: present
        inherit: true
        inRoles:
          - windmill_admin
          - windmill_user
    services:
      additional:
        - selectorType: rw
          updateStrategy: patch
          serviceTemplate:
            metadata:
              name: "cluster"
              annotations:
                external-dns.alpha.kubernetes.io/hostname: infra-pg
              labels:
                io.cilium/lb-pool: pool-infra-pg
            spec:
              type: LoadBalancer
              externalTrafficPolicy: Local