# yaml-language-server: $schema=https://raw.githubusercontent.com/cloudnative-pg/charts/main/charts/cloudnative-pg/values.schema.json
crds:
  create: true
replicaCount: 1
additionalEnv:
  - name: TZ
    value: America/Los_Angeles
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    memory: 200Mi
monitoring:
  grafanaDashboard:
    create: true
    namespace: o11y
  podMonitorEnabled: true
