#!/bin/env bash
[[ $# -ne 2 ]] && { echo "usage: k3s-update-master infra{id} version"; exit 1; }

# set -x
set -eu -o pipefail
id="$1"
version="$2"
[[ "$id" -ge 1 && "$id" -le 3 ]] || { echo "infra id must be between 1..3"; exit 1; }

ssh infra$id "k3sup join --ip '10.10.1.1$id' --server-ip 10.10.1.10 --server --k3s-channel stable --k3s-version '$version' --k3s-extra-args '--disable servicelb,traefik --embedded-registry' --user sobrinho --ssh-key '$HOME/.ssh/raspberrypi_id_rsa'"
