#!/bin/env bash
[[ $# -ne 2 ]] && {
	echo "usage: k3s-update-master infra{id} version"
	exit 1
}

# set -x
set -eu -o pipefail
id="$1"
version="$2"
[[ "$id" -ge 1 && "$id" -le 3 ]] || {
	echo "infra id must be between 1..3"
	exit 1
}

k3sup join \
	--ip "10.10.2.1$id" \
	--server \
	--server-url "https://infra-adm:6443" \
	--k3s-channel stable \
	--k3s-version "$version" \
	--k3s-extra-args '--disable servicelb,traefik --embedded-registry --flannel-backend none --disable-network-policy --disable-kube-proxy --etcd-s3 --etcd-s3-config-secret k3s-etcd-snapshot-secret' \
	--user sobrinho \
	--ssh-key "$HOME/.ssh/raspberrypi_id_rsa"

echo "k3s server infra$id updated to version $version"
