#!/bin/env bash
[[ $# -lt 1 ]] && { echo "usage: seal-secret something-secret.yaml > secrets/something-secret-enc.yaml"; exit 1; }

set -eu -o pipefail

kubeseal -o yaml --controller-name sealed-secrets --controller-namespace kube-system < $1
