#!/bin/env bash
set -eu -o pipefail

KUBECONFIG=$HOME/.kube/config kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml > /tmp/old.yaml
KUBECONFIG=/mnt/library/config/homelab/kubeconfig kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml > /tmp/new.yaml
# kubectl get secret -n kube-system sealed-secrets-key -o yaml

colordiff -u /tmp/old.yaml /tmp/new.yaml