---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    encryption-key: AgCgGMelNPI0sdcrS0ZJf4SW8vVq/ltPIx3o6h2rZgNrr9DbTTnnQZedcyr9ENapyk9hGITqB1v4U0HCBh81LK5d3ZXGmvGJrFv86A52kfHjgCA5ASMRjz19kyfh8n41fX9fs+N0Q6N+grfwFHdKpTslr9/mqlKwollhF9FtuCpFNxqAn90/gLagh+ez9Oefy8q6LPttMbO79YAeD1HOC3a4ppnYPbq3iWgz5c6M4NBvO3U/brrmXDH+WQEKzE0hRsLTl0VgmyWTxr/0yRwSsaxoddx74l5Spu53+laxoJ0ZRdyRCOlAxm7noqyaBZjsCwm7kHVtdzlW+9H/gJXMae11JdG2O521K5RwDChzIw5xhEiQxlX6xkv/YWkqx7Cz2E13uN+MUaXdANPX9LRalnZQsqZWs9paQGFL8BFyDoQ3PghjmaGt+46Yc7rF99MjPoWCbIasDXcJZoevcfbD+tex9Vb6eXCVpyn54RPJIwCkw3gL727NDpkf9yVl0XyJqA0N3bXml9ZXz/qI1Lyf1ogAJu/zD/TGHXD7EaPJyKNGkWcTnvkn2iOaYnl83W1NmfUqiHLfnpbZiWZuOv0Bjfj4LTRvHQeHuE98YFv1FAfIWOvtC25sBXvA5px9b0UrY/yD45Shui+7EwZ6+J09rmTjSregdVgMpWixsKpKfLZVP4Y+OAaxt4nmsQ7GCGEdcBUL4zN4UvVdmHc8HGUgJproCd0cQ9Cm6iBZ+nJRzb0YTQ==
    runners-auth-token: AgAec9zHIup2kXdp4Dl4ym7ekW6Jy/X6CDngmwvl/d5U7xxvNIo/or19UDQEsMRTkh67Bg85Ofia0/8oxF+A3PqvbtcGeXxtYE+2tVn8ZbbN28fo67vqcsVS+XDODjHpMJvdxHuQeCJwCsoHBaEbhLKznTYyqChJokHNX9ESejc7Vlyr4qDs0x21INBfyr3wSVmUBYYCj5iZTzx7muQYUBUPUl8OXzVxRBuO7v/80e2j/ZA5I021F7T9l1WlnYd4Gqah4PrE9KyCxnvRO/Inej25gaLwyMyNdLc2xIGp/FozF8RJUA2Bsig67d8gtaztrm0VLxSQj71w1h/A2Ipx4tqA6OdOuXmw6cHSxINn2nq7COCAm8N90veoHJNErUuauXU64/hELM5CFXeXmBpfa6iJ6/o0KrvVvdNaxTr83UY/wY4YogZHXUXZkMax4hObbB2TugNmmM6R9xqvCFDKHDMSQb/XMWpIQ739av+6094zUcx9vp/xQBAa1gDt+srHLeQYKY7qiZNMxVEO2PEHN7MInw+8KVxKf/sGMBhbcpXlyxt19nIo3WkPipdqzJ2L8qug8w9J3ZEnp3mCRly6uXBmyHlv9zoZ3SJ+xKIbRYEkk1QtzTq3TNOsArFKYPlncwwxvEwQiyve7m1cnleKENk3sz8v/AXK0sffDHA8joh3lK8nGOetmlv0URARV7IE7z6cJyjCwwWswJT728j4lHwheWQqS7gu2EOfiKbSBCZ0qFIpzmlv+jlj5Fe8ZmhAppM=
  template:
    metadata:
      name: n8n-secret
      namespace: n8n
    type: Opaque
