---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secret
  namespace: n8n
spec:
  encryptedData:
    encryption-key: AgB6Iod9CvQlixZvSk58wO8KFchHOS0rDttuDCizhIy+8U6LMkNSGH2+xxFZ1i+5ksFKDVOPs9TqwaQsNgWeyXwixwursGK0zg6mujQxLhu3qhEpKOgB56GFZQVhdAWNl+76qs5nn357rZBYzFlOXbEBy8j/tAKDTM7wC4W2KKLYfDG0m+OWCGBTTLDNeTMD1JIchY5MsoGoVrKWdUKDRseE/cVNRU3+fQ+2XBNEOyft1UpIT3Ssq1ByTZ+4wOSizfkB00CurpYwoHlf8LngXTHbEZRaZX5EJfeYbJBxTRTJW3aYtlSrmaUhQvf42Y/wQtMw3SmHHP9MdIWHxb3oB7T4y37wf6ScMWHjcKbMMs3RMElknmgpcZTOmICcbg+w8CvQnkq+CcUkUQ+AWreHFd0Yo5XWPrN9yVEjzeBzWavf78PB+k4Ct/jm6d/Q1Wyv2USBiMYIXtgt+S0Z6fKlUrfZEC3SPFyKNEUCUnTPJAtVc8bkBcIwxm/U0seif5WmM5aq79BFYGypvH9eg+Am19Ljflw46faX5Zvz6Hcpi6X7DmQ/p0ehnofMKhFqY4kryp0zrsS8iiE5pI8wIayBUchIP4pbEzShCo9sbCnpnLrgpTaI1ZbKQaQfv2SCCE9xJiYUPYwrVP0PPfdIVs7y1RUNcTj2w/ygAsmAG+qtEQevEO1EX6q+0ZyKug1lTWyDboyIpup0fn2wUNZFKyurBoRJMNWq31XXa7dcKw5HUzyCUw==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secret
      namespace: n8n
    type: Opaque
