kind: IngressRoute
apiVersion: traefik.io/v1alpha1
metadata:
  name: cleanuparr-ingress
  namespace: media
  annotations:
    external-dns.kubernetes.io/target: infra-int
spec:
  entryPoints:
    - websecure
    - websecure-ext
  routes:
    - match: Host(`cleanuparr.sobrinho.pt`)
      kind: Rule
      services:
        - name: cleanuparr
          port: app
  tls:
    secretName: cleanuparr-cert
---
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: cleanuparr-cert
  namespace: media
spec:
  secretName: cleanuparr-cert
  dnsNames:
    - cleanuparr.sobrinho.pt
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
