apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - middleware.yaml

patches:
  - target:
      group: apps
      kind: Deployment
    patch: |-
      - op: remove
        path: /spec/replicas
  - target:
      group: apps
      kind: StatefulSet
    patch: |-
      - op: remove
        path: /spec/replicas

transformers:
  - transformer-labels.yaml
