apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware-sablier
spec:
  plugin:
    sablier:
      sablierUrl: http://sablier-sablier.infra.svc.cluster.local:10000
      # group: PLACEHOLDER set by transformer-labels.yaml
      sessionDuration: 10m
      blocking:
        timeout: 30s
