apiVersion: apps/v1
kind: Deployment
metadata:
  name: binner
  namespace: binner
spec:
  selector:
    matchLabels:
      app: binner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: binner
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: binner
          image: ghcr.io/csobrinho/binner-docker:main
          resources:
            limits:
              memory: 384Mi
              cpu: 50m
          ports:
            - containerPort: 8090
          env:
            - name: TZ
              value: America/Los_Angeles
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: binner-data
