# From https://github.com/NVIDIA/gpu-operator/blob/main/deployments/gpu-operator/values.yaml
# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nvidia-gpu-operator

resources:
  - ../../base
  - time-slicing-config-all.yaml
  - kernel-module-params.yaml

helmCharts:
  - name: gpu-operator
    namespace: nvidia-gpu-operator
    releaseName: gpu-operator
    repo: https://nvidia.github.io/gpu-operator
    includeCRDs: true
    version: v26.3.1
    valuesInline:
      nfd:
        enabled: false # Already installed.
      driver:
        enable: false # Already installed.
        # TODO: kernelModuleConfig:
        #   name: "kernel-module-params" # With power saving attributes.
      toolkit:
        enabled: false
      hostPaths:
        driverInstallDir: /usr/local # where Talos puts the driver.
      devicePlugin:
        enabled: true
        config:
          create: false
          name: time-slicing-config-all
          default: any
      dcgmExporter:
        enabled: true
        serviceMonitor:
          enabled: true
      validator:
        plugin:
          env:
            - name: TZ
              value: "America/Los_Angeles"
