# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: prometheus-operator-crds
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus-operator-crds
    namespace: prometheus
    version: 31.0.1
    includeCRDs: true
