# From https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
# From https://github.com/trueforge-org/truecharts/blob/master/charts/stable/mealie/values.yaml
# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress-route.yaml

helmCharts:
  - name: mealie
    repo: https://jvalskis.github.io/mealie-helm/
    releaseName: mealie
    namespace: mealie
    version: 2.0.0
    includeCRDs: true
    valuesInline:
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/mealie-recipes/mealie
                tag: v3.23.1@sha256:5fc5cebedddb3952c1ee78f20faf42ab7e49986813fd314745aa97978a4a13eb
              env:
                TZ: America/Los_Angeles
                BASE_URL: mealie.sobrinho.pt
      persistence:
        data:
          enabled: true
          existingClaim: mealie-data
          advancedMounts:
            main: # the controller with the "main" identifier
              main: # the container with the "main" identifier
                - path: /app/data/
                  readOnly: false

  - name: kopiur-pvc
    repo: oci://ghcr.io/csobrinho/helm-charts
    releaseName: mealie-kopiur
    namespace: mealie
    version: 0.1.0
    valuesInline:
      # yaml-language-server: $schema=https://raw.githubusercontent.com/csobrinho/helm-charts/refs/heads/main/charts/kopiur-pvc/values.schema.json
      uid: 0
      gid: 0
      persistence:
        mealie-data:
          retain: true
          accessMode: ReadWriteOnce
          size: 5Gi
          storageClass: local-data

components:
  - ../../../../components/managed-sablier
