# From https://github.com/trueforge-org/truecharts/blob/master/charts/library/common/values.yaml
# From https://github.com/trueforge-org/truecharts/blob/master/charts/stable/dispatcharr/values.yaml
# yaml-language-server: $schema=https://www.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - deployment.yaml
  - ingress-route.yaml
  - postgresql-database.yaml
  - service.yaml
  - secrets/dispatcharr-secret-enc.yaml

helmCharts:
  - name: kopiur-pvc
    repo: oci://ghcr.io/csobrinho/helm-charts
    releaseName: dispatcharr-kopiur
    namespace: media
    version: 0.1.0
    valuesInline:
      # yaml-language-server: $schema=https://raw.githubusercontent.com/csobrinho/helm-charts/refs/heads/main/charts/kopiur-pvc/values.schema.json
      persistence:
        dispatcharr-data:
          retain: true
          accessMode: ReadWriteOnce
          size: 1Gi
          storageClass: local-db
      backup: # Must run as root.
        mover:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          podSecurityContext:
            fsGroup: 0
      populate:
        mover:
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          podSecurityContext:
            fsGroup: 0

components:
  - ../../../../components/disable-revision-history
